import Link from "next/link";
import "./globals.css";
import { Outfit } from "next/font/google";
import Image from "next/image";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Type Frenzy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} max-w-5xl min-h-screen flex flex-col px-4 w-full lg:px-6 mx-auto`}
      >
        <header className="py-4">
          <nav className="flex justify-between items-center">
            <Link href="/" className="flex items-center gap-2">
              <Image src="/keycap.svg" alt="" width={40} height={40} />
              <span className="font-bold text-lg lg:text-2xl">type-frenzy</span>
            </Link>

            <div className="flex gap-4">
              <Link href="/leaderboard" className="">
                Leaderboard
              </Link>
              <Link href="/sign-in" className="">
                Sign In
              </Link>
            </div>
          </nav>
        </header>
        <main className="flex-1 my-20">{children}</main>
        <footer className="py-4 flex items-center justify-between gap-2">
          <p>
            By{" "}
            <Link
              href="https://benaiahbarango.com"
              target="_blank"
              className="underline"
            >
              Benaiah Barango
            </Link>
          </p>

          <div className="flex items-center gap-4">
            <p>Powered by</p>
            <Link href="https://appwrite.io/" target="_blank">
              <Image
                src="/built-with-appwrite.svg"
                alt="Vercel logo-type"
                width={108}
                height={27}
              />
            </Link>
            <Link href="https://vercel.com/" target="_blank">
              <Image
                src="/vercel-dark.svg"
                alt="Vercel logo-type"
                width={88}
                height={20}
              />
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
